import type { NextPage } from "next";
import Head from "next/head";
import UrbanMap from "@components/Map/map";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>UrbanTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UrbanMap />
    </div>
  );
};

export default Home;
